### PR TITLE
Suggested changes.

### PR DESCRIPTION
**Pull request by larshg**
Hi @mvieth 

Just a few suggestions for easier use in VS.

The timing shows in k-milliseconds is just a personal preference. Its more digestible for me 😄

### CODE REVIEW

**Comment by larshg** [comment]
I'll try to stop now 😁

**Comment by mvieth** [comment]
Using milliseconds instead of nanoseconds is a good idea. Do you know why it is called `kMillisecond`, not just `Millisecond`?

Regarding the OMP benchmark: depending on what should be measured, the option `UseRealTime()` might make sense:
https://github.com/google/benchmark#multithreaded-benchmarks

**Comment by larshg** [comment]
Not really, just seems like some sort of prefix:https://github.com/google/benchmark/blob/4857962394266165790de2266a695f328fc144f3/include/benchmark/benchmark.h#L410

Yes, it seems to be more correct to use UseRealTime.

**Comment by mvieth** [comment]
> Yes, it seems to be more correct to use UseRealTime.

Do you want to add it or should I add it after merging this PR?

**Comment by larshg** [comment]
Please you can add it. I'm out of time for today at least 😄

**Pull request merged**
